#include "RatApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<RatApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

RatApp::RatApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  RatApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  RatApp::associateSyntax(_syntax, _action_factory);
}

RatApp::~RatApp()
{
}

// External entry point for dynamic application loading
extern "C" void RatApp__registerApps() { RatApp::registerApps(); }
void
RatApp::registerApps()
{
  registerApp(RatApp);
}

// External entry point for dynamic object registration
extern "C" void RatApp__registerObjects(Factory & factory) { RatApp::registerObjects(factory); }
void
RatApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void RatApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { RatApp::associateSyntax(syntax, action_factory); }
void
RatApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
